# from base image node
FROM node:8.11-slim

# copying all the files from your file system to container file system
COPY package.json .

# install all dependencies
RUN npm install

# copy oter files as well
COPY ./ .

WORKDIR /app