version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: bring_dev
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
    command: ["npm", "run", "start:dev"]
    ports:
      - "80:5000"
