version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bring_production
    env_file:
      - ./.env
    command: ["npm", "start"]
    ports:
      - "80:5000"
